// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKiiKqKg6dliZXV2rZ-FVR1SFJa93e2k',
    appId: '1:290021143671:web:d222ac68bdf752c4464272',
    messagingSenderId: '290021143671',
    projectId: 'needlink-1a854',
    authDomain: 'needlink-1a854.firebaseapp.com',
    storageBucket: 'needlink-1a854.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiNTYFqBpZ-HcJJ1Q6bGEAat08a2kw0c',
    appId: '1:290021143671:android:fd1d1e9037f2d6f5464272',
    messagingSenderId: '290021143671',
    projectId: 'needlink-1a854',
    storageBucket: 'needlink-1a854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASiLi415ljtU30pdpBmHgkv18UfZVmKfY',
    appId: '1:290021143671:ios:ecf8fdd7ae9cd9ae464272',
    messagingSenderId: '290021143671',
    projectId: 'needlink-1a854',
    storageBucket: 'needlink-1a854.firebasestorage.app',
    iosBundleId: 'com.needlink.needlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASiLi415ljtU30pdpBmHgkv18UfZVmKfY',
    appId: '1:290021143671:ios:ecf8fdd7ae9cd9ae464272',
    messagingSenderId: '290021143671',
    projectId: 'needlink-1a854',
    storageBucket: 'needlink-1a854.firebasestorage.app',
    iosBundleId: 'com.needlink.needlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKiiKqKg6dliZXV2rZ-FVR1SFJa93e2k',
    appId: '1:290021143671:web:656c716bb2174553464272',
    messagingSenderId: '290021143671',
    projectId: 'needlink-1a854',
    authDomain: 'needlink-1a854.firebaseapp.com',
    storageBucket: 'needlink-1a854.firebasestorage.app',
  );

}