// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUSLt2XZiiSjDrTmzjKcbcywjmm9Arah0',
    appId: '1:139807136480:web:3a5d7b0d47cc4faa58ce85',
    messagingSenderId: '139807136480',
    projectId: 'needlink-90a7c',
    authDomain: 'needlink-90a7c.firebaseapp.com',
    storageBucket: 'needlink-90a7c.firebasestorage.app',
    measurementId: 'G-7R5TKQR76K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfvc7OveIskOKc_s2DAe4_5mmMXQL7NHE',
    appId: '1:139807136480:android:a98b38a59c014a5a58ce85',
    messagingSenderId: '139807136480',
    projectId: 'needlink-90a7c',
    storageBucket: 'needlink-90a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVFBYBQbNo7kU8LFV3yy_zovH5_Ow-uY',
    appId: '1:139807136480:ios:eac6e9c33ce1a39d58ce85',
    messagingSenderId: '139807136480',
    projectId: 'needlink-90a7c',
    storageBucket: 'needlink-90a7c.firebasestorage.app',
    iosBundleId: 'com.needlink.needlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlVFBYBQbNo7kU8LFV3yy_zovH5_Ow-uY',
    appId: '1:139807136480:ios:eac6e9c33ce1a39d58ce85',
    messagingSenderId: '139807136480',
    projectId: 'needlink-90a7c',
    storageBucket: 'needlink-90a7c.firebasestorage.app',
    iosBundleId: 'com.needlink.needlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUSLt2XZiiSjDrTmzjKcbcywjmm9Arah0',
    appId: '1:139807136480:web:9c8441e78e57cf0c58ce85',
    messagingSenderId: '139807136480',
    projectId: 'needlink-90a7c',
    authDomain: 'needlink-90a7c.firebaseapp.com',
    storageBucket: 'needlink-90a7c.firebasestorage.app',
    measurementId: 'G-2973V0V3WE',
  );
}
